# Copyright (c) 2019 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
# Author: Sathish Kuttan <sathish.k.kuttan@intel.com>

general:
    name:      Sue Creek

spi:
    device:    /dev/spidev0.0
    max_speed: 9.6     # Max SPI clock frequency 9.6 MHz

gpio:
    reset:     22      # GPIO 22 for resetting device
    wake:      23      # GPIO 23 for wake notification to device
    irq:       27      # GPIO 27 for interrupt notification from device
