name: Backport
on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-18.04
    name: Backport
    steps:
      - name: Backport
        uses: zephyrproject-rtos/action-backport@v1.1.99
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
